name: Deploy Prod

on:
  push:
    branches: [ api/prod ]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - id: 'checkout'
      uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/339690027814/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github@battleword.iam.gserviceaccount.com'
    - name: 'Deploy '
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        source: './api'
        service: 'api-prod'